version: "3"
services:
 db:
  image: mysql:5.7
  ports:
   - 3306:3306
  volumes:
   - ./db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: roodpassutopiaplay
   MYSQL_DATABASE: utopiaplay
   MYSQL_USER: utopiaplay
   MYSQL_PASSWORD: utopiaplay
 php:
  restart: always
  depends_on:
   - db
  build:
   context: .
  ports:
   - 8005:8005
  volumes:
   - ./app:/usr/src/code/app
   - ./vendor:/usr/src/code/vendor
  environment:
   DB_HOST: db
   DB_PORT: 3306
   DB_USER: utopiaplay
   DB_PASSWORD: utopiaplay
   DB_NAME: utopiaplay
